blank_issues_enabled: false

contact_links:
  - name: ðŸŽ§ Support Server
    url: https://discord.gg/YOURSERVER
    about: For general support or questions.

  - name: ðŸ“š ChristmasBot Documentation
    url: https://christmasbot.org/docs
    about: Documentation for ChristmasBot.

  - name: ðŸ“š HalloweenBot Documentation
    url: https://halloweenbot.com/docs
    about: Documentation for HalloweenBot.
